<?php

function setLang($locale) {
  global $lang_meta;
  global $lang_descr;
  global $lang_title;
  global $lang_main;
  global $lang_main2;
  global $lang_main3;
  global $lang_main4;
  global $lang_main5;
  global $lang_main6;
  global $lang_main7;
  global $lang_main8;
  global $lang_main9;
  global $lang_main10;
  global $lang_err1;
  global $lang_err2;
  global $lang_err4;
  global $lang_err5;
  global $lang_err6;
  global $lang_err7;
  global $lang_err8;
  global $lang_err9;
  global $lang_cr1;
  global $lang_cr2;
  global $lang_cr3;
  global $lang_ret;
  global $lang_conf;
  global $lang_open;
  global $lang_text;
  global $lang_theme_dark;
  global $lang_theme_light;
  global $lang_main11;
  global $lang_history;
  global $lang_history_sent;
  global $lang_history_status;
  global $lang_history_viewed;
  global $lang_history_unviewed;
  global $lang_history_empty;
  global $lang_main12;
  global $lang_login;
  global $lang_register;
  global $lang_username;
  global $lang_password;
  global $lang_logout;
  global $lang_signed_in;
  global $lang_auth_required;
  global $lang_auth_invalid;
  global $lang_auth_exists;
  global $lang_auth_username_error;
  global $lang_auth_password_error;
  switch ($locale) {
    case 1:
      $lang_meta="uk";
      $lang_descr="Безпечно дiлись важливими данними";
      $lang_title="Безпечнi повiдомлення";
      $lang_main="Безпечна вiдправка будь яких текстових данних:";
      $lang_main2="введiть вашi важливi даннi i отримайте одноразове посилання на них. Подiлiться цим посиланням з будь ким, будь яким методом. Ваш спiвбесiдник зможе вiдкрити це посилання лише один раз. Даннi не передаються у вiдкритому виглядi, ви лише дiлитесь посиланням. Пiсля вiдкриття все даннi знищуються, тому це посилання не можна вiдкрити вдруге - це i є гарантiєю, що вашi секретнi даннi не були нiким перехопленi та вiдкритi.";
      $lang_main3="Введiть ваш текст сюди";
      $lang_main4="Час життя посилання(годин)";
      $lang_main5="Створити посилання";
      $lang_main6="Завантажити доданий файл";
      $lang_main7="Cвiй пароль(не обов'язково)";
      $lang_main8="Додати файл";
      $lang_main9="Це повiдомлення захищено додатковим паролем.Введiть пароль:";
      $lang_main10="Спробувати ще раз";
      $lang_err1="Помилка! Ви не ввели текст, або ще щось.";
      $lang_err2="Помилка CSRF token. Оновiть сторiнку i спробуйте ще раз.";
      $lang_err4="Упс! Проблема:";
      $lang_err5="Таке посилання просто не icнує. 🤷";
      $lang_err6="Строк життя посилання закiнчився. Воно бiльше не доступно, як i даннi, що були там.";
      $lang_err7="Повiдомлення вже було переглянуто.Залишився тiльки файл.";
      $lang_err8="Ви не ввели пароль для розшифрування повiдомлення.";
      $lang_err9="Не вiрний пароль.Перегляд не зараховано.";
      $lang_cr1="Ось ваше тимчасове посилання:";
      $lang_cr2="Скопiюйте його та передайте кому вважаєте за потрiбне. Це посилання можна буде вiдкрити тiльки один раз.";
      $lang_cr3="Створити ще одне";
      $lang_ret="Повернутися на головну сторiнку";
      $lang_conf="Пiдтвердiть вiдкриття посилання.<br>Пiсля цього воно буде показано один раз и видалено:";
      $lang_open="Вiдкрити посилання";
      $lang_text="Ось текст що був зашифрован:";
      $lang_theme_dark="Темна тема";
      $lang_theme_light="Світла тема";
      $lang_main11="Кількість переглядів";
      $lang_history="Історія повідомлень";
      $lang_history_sent="Надіслано";
      $lang_history_status="Статус";
      $lang_history_viewed="Переглянуто";
      $lang_history_unviewed="Не переглянуто";
      $lang_history_empty="Повідомлень ще немає.";
      $lang_main12="Використати коротке посилання";
      $lang_login="Увійти";
      $lang_register="Зареєструватися";
      $lang_username="Ім’я користувача";
      $lang_password="Пароль";
      $lang_logout="Вийти";
      $lang_signed_in="Ви увійшли як";
      $lang_auth_required="Увійдіть, щоб створювати повідомлення.";
      $lang_auth_invalid="Невірне ім’я користувача або пароль.";
      $lang_auth_exists="Це ім’я користувача вже використовується.";
      $lang_auth_username_error="Ім’я користувача має містити 3–32 літери, цифри, крапки, дефіси або символи підкреслення.";
      $lang_auth_password_error="Пароль має містити щонайменше 10 символів.";
      break;
    case 2:
      $lang_meta="ru";
      $lang_descr="Безопасно делись важными данными";
      $lang_title="Безопасные сообщения";
      $lang_main="Безпасная отправка любых текстовых данных:";
      $lang_main2="введите ваши важные данные и получите одноразовую ссылку на них. Поделитесь этой ссылкой с кем угодно, любым способом. Ваш собеседник сможет открыть эту ссылку только один раз. Данные не передаются в открытом виде, вы лишь делитесь ссылкой. После открытия все данные уничтожаются, потому эту ссылку нельзя открыть снова - это и есть гарантией, что ваши секретные данные не были никем перехвачены и открыты.";
      $lang_main3="Введите ваш текст сюда";
      $lang_main4="Время жизни ссылки(часов)";
      $lang_main5="Создать ссылку";
      $lang_main6="Скачать вложенный файл";
      $lang_main7="Свой пароль(не обязат.)";
      $lang_main8="Вложить файл";
      $lang_main9="Сообщение защищено доп.паролем.Введите пароль:";
      $lang_main10="Проробовать еще раз";
      $lang_err1="Ошибка! Вы не ввели текст, или еще что-то.";
      $lang_err2="Ошибка CSRF token. Обновите страницу и попробуйте еще раз.";
      $lang_err4="Упс! Проблема:";
      $lang_err5="Такая ссылка просто не существует 🤷";
      $lang_err6="Срок жизни ссылки закончился. Оно больше не доступно, як и данные, что были там.";
      $lang_err7="Сообщение уже было просмотрено.Остался только файл.";
      $lang_err8="Вы не ввели пароль для расшифровки сообщения";
      $lang_err9="Неправильный пароль.Просмотр не засчитан.";
      $lang_cr1="вот ваша временная ссылка:";
      $lang_cr2="Скопируйте его и передайте кому считаете нужным. Эта ссылка может быть открыта только один раз.";
      $lang_cr3="Создать еще одно";
      $lang_ret="Вернуться на главную страницу";
      $lang_conf="Подтвердите открытие ссылки.<br>После этого оно будет показано один раз и удалено:";
      $lang_open="Открыть ссылку";
      $lang_text="Вот текст что был зашифрован:";
      $lang_theme_dark="Тёмная тема";
      $lang_theme_light="Светлая тема";
      $lang_main11="Количество просмотров";
      $lang_history="История сообщений";
      $lang_history_sent="Отправлено";
      $lang_history_status="Статус";
      $lang_history_viewed="Просмотрено";
      $lang_history_unviewed="Не просмотрено";
      $lang_history_empty="Сообщений пока нет.";
      $lang_main12="Использовать короткую ссылку";
      $lang_login="Войти";
      $lang_register="Зарегистрироваться";
      $lang_username="Имя пользователя";
      $lang_password="Пароль";
      $lang_logout="Выйти";
      $lang_signed_in="Вы вошли как";
      $lang_auth_required="Войдите, чтобы создавать сообщения.";
      $lang_auth_invalid="Неверное имя пользователя или пароль.";
      $lang_auth_exists="Это имя пользователя уже используется.";
      $lang_auth_username_error="Имя пользователя должно содержать 3–32 буквы, цифры, точки, дефисы или символы подчеркивания.";
      $lang_auth_password_error="Пароль должен содержать не менее 10 символов.";
      break;
    case 3:
      $lang_meta="en";
      $lang_descr="Safely share your data";
      $lang_title="Secuire messages";
      $lang_main="Secure send your important data:";
      $lang_main2="enter your text data and get one time link for it. Share this link with anybody you want via any method you want. The receiver will be able to open the link only once. Your data doesn't being tranfered by plaintext, you are just sharing the link. After link is opened,the data is being destroyed, so this link can't be opened again anymore - is guarantees your secret data wasn't intercepted and opened by somebody.";
      $lang_main3="Enter your text data here";
      $lang_main4="Link lifetime(hours)";
      $lang_main5="Create link";
      $lang_main6="Download attached file";
      $lang_main7="Set your passw.(if you want)";
      $lang_main8="Attach a file";
      $lang_main9="The message is protected by additional password.Enter the password:";
      $lang_main10="Try again";
      $lang_err1="Error! You haven't entered text, or something else.";
      $lang_err2="CSRF token error. Reload the page and try again.";
      $lang_err4="Oops! A problem:";
      $lang_err5="This link doesn't exist anymore! 🤷";
      $lang_err6="Link's lifetime has expired. It is unavailable, like the data it contained.";
      $lang_err7="The message have already been seen.Only attached file left.";
      $lang_err8="You didn't type a password.";
      $lang_err9="Wrong password. The view was not consumed.";
      $lang_cr1="this is your temporarily link:";
      $lang_cr2="Copy it and share with anybody you want. This link can be opened just once.";
      $lang_cr3="Create another one";
      $lang_ret="Return to main page";
      $lang_conf="Confirm link opening.<br>After that you will see the stored message once and it will be deleted.";
      $lang_open="Open link";
      $lang_text="Here is your data that was encrypted:";
      $lang_theme_dark="Dark mode";
      $lang_theme_light="Light mode";
      $lang_main11="Number of views";
      $lang_history="Message history";
      $lang_history_sent="Sent";
      $lang_history_status="Status";
      $lang_history_viewed="Viewed";
      $lang_history_unviewed="Not viewed";
      $lang_history_empty="No messages have been sent yet.";
      $lang_main12="Use short URL";
      $lang_login="Log in";
      $lang_register="Create account";
      $lang_username="Username";
      $lang_password="Password";
      $lang_logout="Log out";
      $lang_signed_in="Signed in as";
      $lang_auth_required="Log in to create messages.";
      $lang_auth_invalid="Invalid username or password.";
      $lang_auth_exists="That username is already in use.";
      $lang_auth_username_error="Username must contain 3–32 letters, numbers, periods, hyphens, or underscores.";
      $lang_auth_password_error="Password must be at least 10 characters long.";
      break;
  }
}
